name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug dependabot condition
        env:
          GH_ACTOR: ${{ github.triggering_actor }}
          GH_EVENT: ${{ github.event_name }}
        run: |
          echo "github.actor: $GH_ACTOR"
          echo "github.event_name: $GH_EVENT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Skip duplicates and docs
        id: skip
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md", "LICENSE", ".gitignore", ".editorconfig", ".idea/**"]'

      - name: Validate gradle wrapper
        if: steps.skip.outputs.should_skip != 'true'
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        if: steps.skip.outputs.should_skip != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: gradle
          distribution: temurin

      - name: Build with gradle
        if: steps.skip.outputs.should_skip != 'true'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew build jacocoTestReport coveralls --scan
