name: Test Report

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit Tests
          path: '**/build/test-results/**/TEST*.xml'
          reporter: java-junit
          
      - run: ls -la
      
      - name: Unzip test results
        run: unzip test-results.zip
      
      - run: ls -la
      
      - name: Publish Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: 'build/reports/jacoco/coverage/coverage.xml'
